### ISSUE TITLE
Defining adv7513 resource for a new board with subsignals different from DE10-Nano

### ISSUE THREAD

**Issue by AsuMagic** [nmigen/nmigen-boards#122]
While implementing a board file for the [Cyclone V GX starter kit](https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&No=830), I noticed that it uses the same HDMI transmitter as the DE10-Nano as defined [here](https://github.com/nmigen/nmigen-boards/blob/master/nmigen_boards/de10_nano.py#L48).

The pin names are identical, but the GX starter kit does not have audio related pins wired in. Specifically, these are missing:
- `HDMI_I2S0` (`i2s0`)
- `HDMI_MCLK` (`mclk`)
- `HDMI_LRCLK` (`lrclk`)
- `HDMI_SCLK` (`sclk`)

I'm assuming that resources under a certain name (in this case `"adv7513"`) should keep consistent subsignals across multiple boards. How should I handle this?

Furthermore, the DE10-Nano dedicates pins for the adv7513 I2C, like so:
```python
            Subsignal("scl", Pins("U10", dir="o")),
            Subsignal("sda", Pins("AA4", dir="io")),
```
In the GX starter kit, this is not the case, as the `I2C_SCL` (`PIN_B7`) and `I2C_SDA` (`PIN_G11`) pins are used for the programmable oscillator, the audio interface, among other things, i.e. should be reused across several resources.  
Since defining multiple identical pins assignments or otherwise reusing pins appears to be impossible, how should I proceed?

**Comment by whitequark** [comment]
Good question. There is such a thing as "optional pins"; I/O cores may use `hasattr` and friends to check if they e.g. have I2S related pins. This is not ideal, but this transmitter is a very niche device, so I believe it would be OK to simply omit them for now.
