### ISSUE TITLE
Nexys4DDR: I/O standard should be different for some switches

### ISSUE THREAD

**Issue by neuschaefer** [nmigen/nmigen-boards#176]
On the Nexys4DDR board, two of the 16 slide switches (SW8/T8, SW9/U8) are connected to 1.8V rather than 3.3V:

![nexys-sw](https://user-images.githubusercontent.com/1021512/127770769-616f1131-c924-4b3b-9907-84e255d76da5.png)

This is currently not reflected in the [board definition](https://github.com/nmigen/nmigen-boards/blob/master/nmigen_boards/nexys4ddr.py#L24), but probably should be.

**Comment by whitequark** [comment]
Would you be willing to send a PR? Here is an example of how to use `SwitchResources` with two different IO standards: https://github.com/nmigen/nmigen-boards/blob/6bbd2dd89f78f38f11ec497e34d4cddf8aae88dc/nmigen_boards/ecp5_5g_evn.py#L58-L61

**Comment by neuschaefer** [comment]
Yes, will do. Thanks for the guidance.
