### ISSUE TITLE
Option to factor out "clk" from "spi_flash" on Lattice ECP5

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen-boards#37]
<a href="https://github.com/HarryHo90sHK"><img src="https://avatars3.githubusercontent.com/u/6345728?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HarryHo90sHK](https://github.com/HarryHo90sHK)**
_Monday Dec 23, 2019 at 08:22 GMT_
_Originally opened as https://github.com/m-labs/nmigen-boards/pull/38_

----

According to Section 6.1.2 of an [official ECP5 manual](http://www.latticesemi.com/view_document?document_id=50462), only the on-chip oscillator MCLK is available as the SPI clock when in Master SPI mode by default. To use any user clock as the SPI clock, a USRMCLK Instance must be instantiated and there is no need to request for the clock from Ball U3. Requesting for such clock will lead to an error as [reported by @xobs](https://github.com/YosysHQ/nextpnr/issues/290#issuecomment-536397715) on the nextpnr repo.

Therefore, I would like to suggest modification on [memory.py](https://github.com/HarryHo90sHK/nmigen-boards/blob/ecp5_spi/nmigen_boards/resources/memory.py) such that there is an option to add the SPI flash resources to a platform (not only ECP5) without the clock. Although this modification has been used to successfully build and flash a bitstream on an ECP5 board (the example was an [SPI reader module](https://github.com/HarryHo90sHK/nmigen-stdio/blob/spi/nmigen_stdio/spiflash.py#L201-L309) on my nmigen-stdio fork), I cannot deny that there is room for improvement on my code for this pull request. 

I look forward to seeing further comments, thanks.

**See also: my [pull request](https://github.com/m-labs/nmigen-stdio/pull/2) on nmigen-stdio for a SPI controller.**

----

_**[HarryHo90sHK](https://github.com/HarryHo90sHK)** included the following code: https://github.com/m-labs/nmigen-boards/pull/38/commits_

**Comment by whitequark** [comment]
This is now tracked at https://github.com/nmigen/nmigen/issues/525.
