### ISSUE TITLE
Add Digilent Genesys2 board.

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen-boards#38]
<a href="https://github.com/peteut"><img src="https://avatars3.githubusercontent.com/u/1288741?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peteut](https://github.com/peteut)**
_Thursday Jan 02, 2020 at 01:49 GMT_
_Originally opened as https://github.com/m-labs/nmigen-boards/pull/39_

----

The `Blinky` test works fine on my board.

----

_**[peteut](https://github.com/peteut)** included the following code: https://github.com/m-labs/nmigen-boards/pull/39/commits_

**Comment by whitequark** [comment]
@peteut Could you please resubmit the PR against this repository? It looks good overall, but I'd like you to make a few minor changes.

**Comment by igrr** [comment]
Seems to be fixed by https://github.com/nmigen/nmigen-boards/pull/49.
