### ISSUE TITLE
Add Alchitry Au board definition

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen-boards#43]
<a href="https://github.com/TiltMeSenpai"><img src="https://avatars1.githubusercontent.com/u/4134542?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TiltMeSenpai](https://github.com/TiltMeSenpai)**
_Tuesday Jan 14, 2020 at 23:06 GMT_
_Originally opened as https://github.com/m-labs/nmigen-boards/pull/44_

----

Notes:
- Alchitry Au requires a loader program from Alchitry. I tried to follow a pattern similar to what nmigen uses to locate Yosys/Vivado but I'm not sure if that's the right approach
- DDR3 is untested. The pins are copied from the schematic so I may have gotten something wrong there.
- There's also an io shield for the Au with a few buttons, some 7 segment displays, and a bunch of LED's. I was debating adding a resource for that, similar to how the icebreaker pmod's are defined, but ultimately decided I was gambling whether I'd finish that pin definition before running out of motivation. Let me know if you'd like that pin definition in this PR and I'll try to add it.

----

_**[TiltMeSenpai](https://github.com/TiltMeSenpai)** included the following code: https://github.com/m-labs/nmigen-boards/pull/44/commits_

**Comment by whitequark** [comment]
Fixed in #48.
